from opentrons import protocol_api 
metadata = { 
    'protocolName': 'Golden Gate', 
    'author': 'John Bryant <jbryant2@vt.edu>', 
    'description': 'Protocol for performing PCR reactions and Plasmid assembly for TIR1 and AFB mutants', 
    'apiLevel': '2.10' 
    } 
def run(protocol: protocol_api.ProtocolContext): 
    tiprack1 = protocol.load_labware('opentrons_96_tiprack_300ul', '9') 
    tiprack3 = protocol.load_labware('opentrons_96_tiprack_10ul', '5') 
    watertuberack = protocol.load_labware('opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical','3') 
    tuberack2 = protocol.load_labware('opentrons_24_tuberack_nest_1.5ml_snapcap','2') 
    secondarydils = protocol.load_labware('opentrons_96_aluminumblock_generic_pcr_strip_200ul','4') 
    tc_mod = protocol.load_module('Thermocycler Module') 
    pcrplate = tc_mod.load_labware('nest_96_wellplate_100ul_pcr_full_skirt') 
    temp_module = protocol.load_module('temperature module', 1) 
    cold_tuberack = temp_module.load_labware('opentrons_24_aluminumblock_generic_2ml_screwcap', label='Temperature-Controlled Tubes') 
    temp_module.set_temperature(4) 
    tc_mod.open_lid() 
    right_pipette = protocol.load_instrument('p300_single','right',tip_racks=[tiprack1]) 
    left_pipette = protocol.load_instrument('p10_single','left',tip_racks = [tiprack3]) 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(8.75, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(8.75, pcrplate['A6'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(8.75, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(8.75, pcrplate['B6'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(8.75, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(8.75, pcrplate['A5'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(8.75, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(8.75, pcrplate['B5'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['A1'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['A6'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['A6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['A2'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['A6'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['A6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['A3'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['B6'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['B6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['A4'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['B6'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['B6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['A5'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['A5'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['A5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['A6'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['A5'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['A5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['B1'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['B5'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['B5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['B2'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['B5'], rate=2.0) 
    left_pipette.mix(3,2,pcrplate['B5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['B3'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['A6'], rate=2.0) 
    left_pipette.mix(3,3,pcrplate['A6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['B4'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['B6'], rate=2.0) 
    left_pipette.mix(3,3,pcrplate['B6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['B5'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['A5'], rate=2.0) 
    left_pipette.mix(3,3,pcrplate['A5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.0, tuberack2['B6'], rate=2.0) 
    left_pipette.dispense(1.0, pcrplate['B5'], rate=2.0) 
    left_pipette.mix(3,3,pcrplate['B5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(0.75, pcrplate['A6'], rate=2.0) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(0.75, pcrplate['B6'], rate=2.0) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(0.75, pcrplate['A5'], rate=2.0) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(0.75, pcrplate['B5'], rate=2.0) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(12.5, cold_tuberack['D6'], rate=2.0) 
    right_pipette.dispense(12.5, pcrplate['A6'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(12.5, cold_tuberack['D6'], rate=2.0) 
    right_pipette.dispense(12.5, pcrplate['B6'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(12.5, cold_tuberack['D6'], rate=2.0) 
    right_pipette.dispense(12.5, pcrplate['A5'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(12.5, cold_tuberack['D6'], rate=2.0) 
    right_pipette.dispense(12.5, pcrplate['B5'], rate=2.0) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,15.5,pcrplate['A6']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,15.5,pcrplate['B6']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,15.5,pcrplate['A5']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,15.5,pcrplate['B5']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    tc_mod.deactivate() 
    temp_module.deactivate() 
    protocol.pause('move to gradient thermocycler. set gradiet to be between 56.892690113059615 and 70.46866676736803. Extension time should be 128.73000000000002 seconds. Follow normal parameters for everything else. A1 is cool, A8 is hot.') 
    temp_module.set_temperature(4) 
    tc_mod.set_block_temperature(4) 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(18, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(18, pcrplate['A6'], rate=2.0) 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(18, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(18, pcrplate['B6'], rate=2.0) 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(18, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(18, pcrplate['A5'], rate=2.0) 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(18, watertuberack['A1'], rate=2.0) 
    right_pipette.dispense(18, pcrplate['B5'], rate=2.0) 
    right_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(5, cold_tuberack['D4'], rate=2.0) 
    left_pipette.dispense(5, pcrplate['A6'], rate=2.0) 
    left_pipette.mix(3,10,pcrplate['A6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(5, cold_tuberack['D4'], rate=2.0) 
    left_pipette.dispense(5, pcrplate['B6'], rate=2.0) 
    left_pipette.mix(3,10,pcrplate['B6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(5, cold_tuberack['D4'], rate=2.0) 
    left_pipette.dispense(5, pcrplate['A5'], rate=2.0) 
    left_pipette.mix(3,10,pcrplate['A5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(5, cold_tuberack['D4'], rate=2.0) 
    left_pipette.dispense(5, pcrplate['B5'], rate=2.0) 
    left_pipette.mix(3,10,pcrplate['B5']) 
    left_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,35.5,pcrplate['A6']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,35.5,pcrplate['B6']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,35.5,pcrplate['A5']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,35.5,pcrplate['B5']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    tc_mod.close_lid() 
    tc_mod.set_lid_temperature(105) 
    tc_mod.set_block_temperature(37,0,30, block_max_volume = 50) 
    tc_mod.set_block_temperature(80,0,20, block_max_volume = 50) 
    tc_mod.set_block_temperature(4, block_max_volume = 50) 
    tc_mod.open_lid() 
    temp_module.deactivate() 
    tiprack3.reset() 
    tiprack3 = protocol.load_labware('opentrons_96_tiprack_10ul', '6') 
    protocol.pause('REFILL TIP RACKS, and wait until its time to dispense the product') 
    temp_module.set_temperature(4) 
    left_pipette.flow_rate.aspirate = 50 
    right_pipette.flow_rate.aspirate = 50 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(30,cold_tuberack['D2']) 
    right_pipette.dispense(30,cold_tuberack['C4']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    left_pipette.flow_rate.aspirate = 10 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(3,cold_tuberack['C6']) 
    left_pipette.dispense(3,cold_tuberack['C4']) 
    left_pipette.mix(3,10,cold_tuberack['C4']) 
    left_pipette.flow_rate.aspirate = 50 
    left_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(22.874018691588777, watertuberack['A1']) 
    right_pipette.dispense(22.874018691588777, secondarydils['A6']) 
    right_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(6, pcrplate['A6']) 
    left_pipette.dispense(6, secondarydils['A6']) 
    left_pipette.mix(3,3,secondarydils['A6']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.mix(3,7.624672897196259,secondarydils['A6']) 
    left_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(20, pcrplate['B6']) 
    right_pipette.dispense(20, secondarydils['B6']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.aspirate(22.820149253731344, watertuberack['A1']) 
    right_pipette.dispense(22.820149253731344, secondarydils['A5']) 
    right_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(6, pcrplate['A5']) 
    left_pipette.dispense(6, secondarydils['A5']) 
    left_pipette.mix(3,3,secondarydils['A5']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.mix(3,7.606716417910448,secondarydils['A5']) 
    left_pipette.drop_tip() 
    protocol.pause('Clear off PCR plate and set up final Golden Gate assembly Tubes') 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(5.68, watertuberack['A1']) 
    left_pipette.dispense(5.68, pcrplate['B8']) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(2.0, secondarydils['A6']) 
    left_pipette.dispense(2.0, pcrplate['B8']) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.65,cold_tuberack['C4']) 
    left_pipette.dispense(1.65,pcrplate['B8']) 
    left_pipette.mix(3,8,pcrplate['B8']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1,cold_tuberack['D5']) 
    left_pipette.dispense(1,pcrplate['B8']) 
    left_pipette.mix(3,9,pcrplate['B8']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1,cold_tuberack['C5']) 
    left_pipette.dispense(1,pcrplate['B8']) 
    left_pipette.mix(3,9,pcrplate['B8']) 
    left_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,15,pcrplate['B8']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(5.68, watertuberack['A1']) 
    left_pipette.dispense(5.68, pcrplate['B8']) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.6666666666666667, secondarydils['B6']) 
    left_pipette.dispense(1.6666666666666667, pcrplate['B8']) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.65,cold_tuberack['C4']) 
    left_pipette.dispense(1.65,pcrplate['B8']) 
    left_pipette.mix(3,8,pcrplate['B8']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1,cold_tuberack['D5']) 
    left_pipette.dispense(1,pcrplate['B8']) 
    left_pipette.mix(3,9,pcrplate['B8']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1,cold_tuberack['C5']) 
    left_pipette.dispense(1,pcrplate['B8']) 
    left_pipette.mix(3,9,pcrplate['B8']) 
    left_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,15,pcrplate['B8']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(5.68, watertuberack['A1']) 
    left_pipette.dispense(5.68, pcrplate['B8']) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(2.0, secondarydils['A5']) 
    left_pipette.dispense(2.0, pcrplate['B8']) 
    left_pipette.blow_out() 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1.65,cold_tuberack['C4']) 
    left_pipette.dispense(1.65,pcrplate['B8']) 
    left_pipette.mix(3,8,pcrplate['B8']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1,cold_tuberack['D5']) 
    left_pipette.dispense(1,pcrplate['B8']) 
    left_pipette.mix(3,9,pcrplate['B8']) 
    left_pipette.drop_tip() 
    left_pipette.pick_up_tip() 
    left_pipette.aspirate(1,cold_tuberack['C5']) 
    left_pipette.dispense(1,pcrplate['B8']) 
    left_pipette.mix(3,9,pcrplate['B8']) 
    left_pipette.drop_tip() 
    right_pipette.pick_up_tip() 
    right_pipette.mix(3,15,pcrplate['B8']) 
    right_pipette.blow_out() 
    right_pipette.drop_tip() 
    tc_mod.close_lid() 
    tc_mod.set_lid_temperature(temperature = 105) 
    profile = [ 
        {'temperature': 37, 'hold_time_seconds': 180}, 
        {'temperature': 16, 'hold_time_seconds': 240}] 
    tc_mod.execute_profile(steps=profile, repetitions=25, block_max_volume=15) 
    tc_mod.set_block_temperature(50, hold_time_minutes=5, block_max_volume=15) 
    tc_mod.set_block_temperature(80, hold_time_minutes=5, block_max_volume=15) 
    tc_mod.set_block_temperature(4) 
    protocol.pause('wait until ready to dispense assemblies') 
    tc_mod.open_lid() 
    protocol.pause('just take them out manually...') 
